{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "#import matplotlib.pyplot as plt\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import accuracy_score, confusion_matrix\n",
    "from sklearn.model_selection import GridSearchCV, KFold\n",
    "from sklearn.neural_network import MLPClassifier\n",
    "from sklearn.neural_network import MLPRegressor\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.neighbors import KNeighborsRegressor\n",
    "\n",
    "\n",
    "import warnings\n",
    "warnings.simplefilter(action='ignore', category=FutureWarning)\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "File exists: True\n",
      "Load data from tictac_final\n",
      "(958, 9)\n",
      "(958, 1)\n"
     ]
    }
   ],
   "source": [
    "#use this set for classification\n",
    "file_path = 'tictactoedatasets/tictac_final.txt'\n",
    "print('File exists:', os.path.exists(file_path))\n",
    "print(\"Load data from tictac_final\")\n",
    "np.arr = np.loadtxt(file_path)\n",
    "\n",
    "X = np.arr[:, :9]\n",
    "Y = np.arr[:, 9:]\n",
    "\n",
    "print(X.shape)\n",
    "print(Y.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "File exists: True\n",
      "Load data from tictac_multi\n",
      "(6551, 9)\n",
      "(6551, 9)\n"
     ]
    }
   ],
   "source": [
    "#use this \n",
    "file_path = 'tictactoedatasets/tictac_multi.txt'\n",
    "print('File exists:', os.path.exists(file_path))\n",
    "print(\"Load data from tictac_multi\")\n",
    "np.arr = np.loadtxt(file_path)\n",
    "\n",
    "X = np.arr[:, :9]\n",
    "Y = np.arr[:, 9:]\n",
    "\n",
    "print(X.shape)\n",
    "print(Y.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1310, 9) (1310, 9)\n",
      "(5241, 9) (5241, 9)\n"
     ]
    }
   ],
   "source": [
    "x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.8)\n",
    "print (x_train.shape, y_train.shape)\n",
    "print (x_test.shape, y_test.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def _init_KNN_clf():\n",
    "    #intialize paramter grid for grid search\n",
    "    param_grid = [{\n",
    "        'n_neighbors': [3,5,7,9],\n",
    "        'weights': ['uniform', 'distance']\n",
    "    }]\n",
    "    \n",
    "    #initialize cross validation generator\n",
    "    kfd = KFold(n_splits = 10, shuffle = True, random_state = 1)\n",
    "    \n",
    "    #initialize knn classifier with default params (n_neighbors=5 by default) \n",
    "    iter_clf = KNeighborsClassifier()\n",
    "    \n",
    "    #run grid search to find best hyperparams for classifier\n",
    "    clf = GridSearchCV(iter_clf, param_grid, scoring = 'accuracy', cv=kfd)\n",
    "    \n",
    "    return clf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "def _init_KNN_reg():\n",
    "    #intialize paramter grid for grid search\n",
    "    param_grid = [{\n",
    "        'n_neighbors': [3,5,7,9],\n",
    "        'weights': ['uniform', 'distance']\n",
    "    }]\n",
    "    #initialize cross validation generator\n",
    "    kfd = KFold(n_splits = 10, shuffle = True, random_state = 1)\n",
    "    \n",
    "    #initialize knn regressor with default params (n_neighbors=5 by default)\n",
    "    iter_reg = KNeighborsRegressor()\n",
    "    \n",
    "    #run grid search to find best hyperparams for regressor\n",
    "    reg = GridSearchCV(iter_reg, param_grid, scoring = 'accuracy', cv=kfd)\n",
    "    \n",
    "    return reg"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "def KNN_classifier(x_train, y_train, x_test, y_test):\n",
    "    clf = _init_KNN_clf()\n",
    "    clf.fit(x_train, y_train)\n",
    "    \n",
    "    best_score = clf.best_score_\n",
    "    best_params = clf.best_params_\n",
    "    best_esti = clf.best_estimator_\n",
    "    y_pred = clf.predict(x_test)\n",
    "    \n",
    "    #print (\"The best score is: \")\n",
    "    #print(best_score)\n",
    "    print(\"The best parameters are: \")\n",
    "    print(best_params)\n",
    "    \n",
    "    test_acc = accuracy_score(y_test, y_pred)\n",
    "    print('Test accuracy:', test_acc)\n",
    "    \n",
    "    \n",
    "    #generate confusion matrix from testing set predictions, set normalize to true so rows will sum to 1\n",
    "    cm = confusion_matrix(y_test, y_pred, normalize = 'true')\n",
    "    #cm = cm/cm.astype(np.float).sum(axis = 1)\n",
    "    \n",
    "    print(\"Confusion Matrix: \")\n",
    "    print(cm)\n",
    "    \n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "metadata": {},
   "outputs": [],
   "source": [
    "def KNN_regressor(x_train, y_train, x_test, y_test):\n",
    "    reg = _init_KNN_reg()\n",
    "    reg.fit(x_train, y_train)\n",
    "    \n",
    "    best_params = reg.best_params_\n",
    "   \n",
    "    \n",
    "    #print (\"The best score is: \")\n",
    "    #print(best_score)\n",
    "    print(\"The best parameters are: \")\n",
    "    print(best_params)\n",
    "    optimalreg = KNeighborsRegressor(n_neighbors = best_params['n_neighbors'], weights = best_params['weights'])\n",
    "    optimalreg.fit(x_train,y_train)\n",
    "    \n",
    "    y_pred = optimalreg.predict(x_test) #generate predictions on testing set\n",
    "    y_pred = np.where(y_pred > 0.5, 1, 0) #round values to either 0 or 1\n",
    "    \n",
    "    total_acc = np.zero(9)\n",
    "    print(x_test.shape)\n",
    "    for i in range(9):\n",
    "        total_acc[i] = accuracy_score(y_test[:,i], y_pred[:,i], normalize=False)\n",
    "    print(total_acc)\n",
    "    acc = np.sum(total_acc) / (np.shape(y_test)[0] * 9)\n",
    "    print (\"Accurayc knn: {0}\".format(acc))\n",
    "    \n",
    "    #test_acc = accuracy_score(y_test, y_pred)\n",
    "    #print('Test accuracy:', test_acc)\n",
    "    \n",
    "    \n",
    "    #generate confusion matrix from testing set predictions, set normalize to true so rows will sum to 1\n",
    "   # cm = confusion_matrix(y_test, y_pred, normalize = 'true')\n",
    "    #cm = cm/cm.astype(np.float).sum(axis = 1)\n",
    "    \n",
    "   # print(\"Confusion Matrix: \")\n",
    "   # print(cm)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The best score is: \n",
      "0.9057894736842105\n",
      "The best params are: \n",
      "{'n_neighbors': 7, 'weights': 'distance'}\n",
      "Test accuracy: 0.8800521512385919\n",
      "Confusion Matrix is: \n",
      "[[0.68       0.32      ]\n",
      " [0.00813008 0.99186992]]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\neighbors\\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().\n",
      "  return self._fit(X, y)\n"
     ]
    }
   ],
   "source": [
    "KNN_classifier(x_train, y_train, x_test, y_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 761, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 221, in __call__\n",
      "    sample_weight=sample_weight,\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 264, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 211, in accuracy_score\n",
      "    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n",
      "  File \"C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 95, in _check_targets\n",
      "    type_true, type_pred\n",
      "ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\Preston Goren\\Anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_search.py:972: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan]\n",
      "  category=UserWarning,\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The best parameters are: \n",
      "{'n_neighbors': 3, 'weights': 'uniform'}\n",
      "(5241, 9)\n",
      "[4549. 4547. 4494. 4511. 4601. 4483. 4490. 4484. 4529.]\n",
      "Accurayc knn: 0.8626004367275117\n"
     ]
    }
   ],
   "source": [
    "KNN_regressor(x_train, y_train, x_test, y_test)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
